<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />
<meta name="description" content="In Nederland bepaalt uiteindelijk een coalitie het beleid, en niet de onafhankelijke partijen. Op deze website vind je de coalitie die het beste je mening realiseert."/>
		
<link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico" />
<link rel="stylesheet" type="text/css" href="include/styles.css" />

<!--[if lte IE 7]>
			<link href="include/ie.css" rel="stylesheet" type="text/css" />
<![endif]-->

<!--[if IE 6]>
		<script type="text/javascript"> 
			/*Load jQuery if not already loaded*/ if(typeof jQuery == 'undefined'){ document.write("<script type=\"text/javascript\"   src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></"+"script>"); var __noconflict = true; } 
			var IE6UPDATE_OPTIONS = {
				icons_path: "ie6update/images/"
			}
		</script>
		<script type="text/javascript" src="ie6update/ie6update.js"></script>
		<![endif]-->



<?php include('content.php'); ?>