<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" />

<link rel="Shortcut Icon" href="favicon.ico" />
<link rel="stylesheet" type="text/css" href="include/jtip.css" />
<link rel="stylesheet" type="text/css" href="include/styles.css" />

<script type="text/javascript" src="include/hoverhelp.js"></script>
<script type="text/javascript" src="include/jquery.js"></script>
<script type="text/javascript" src="include/jtip.js"></script>

	<!--[if lte IE 6]>
            <link href="include/styles_ie.css" rel="stylesheet" media="screen" type="text/css" />
        <![endif]-->
        <!--[if IE 7]>
            <link href="include/styles_ie.css" rel="stylesheet" media="screen" type="text/css" />
	<![endif]-->

<link rel="stylesheet" type="text/css" href="css/hoverbox.css">
        <!--[if IE 7]>
            <link href="css/hoverbox_ie.css" rel="stylesheet" media="screen" type="text/css" />
	<![endif]-->

<?php include('content.php'); ?>